### ISSUE TITLE
Looking for documentation

### ISSUE THREAD

**Issue by frenchfish** [dr4k0nia/Origami#5]
Hello how I can contact with you&

**Comment by dr4k0nia** [comment]
Hi, the code is mostly documented. If you have any specific questions you can ask them in this issue.

**Comment by frenchfish** [comment]
I don't know where did you get magic numbers? class RelocLoader
byte* basePtr = (byte*) 6969696969L;

// Placeholder for payload size
byte[] buffer = new byte[0x1337c0de];

**Comment by dr4k0nia** [comment]
These values are placeholders they dont serve any other purpose. They are replaced during image creation, which happens in the CustomManagedPEFileBuilder.

**Comment by frenchfish** [comment]
> These values are placeholders they dont serve any other purpose. They are replaced during image creation, which happens in the CustomManagedPEFileBuilder.

thanks
